ipfs/js-ipfs-unixfs

README.md

This patch fixes the hyperlink that leads to https://travis-ci.org/ipfs/js-ipfs-unixfs
Without this patch https://www.npmjs.com/package/ipfs-unixfs looks slightly wrong.

fix a minor typo in the Markdown code of Travis CI build testing status

---

.npmignore

Fixing issue with #8 as the `dist` directory should also be published to npm. Thanks @dignifiedquire for pointing that out.

Remove dist folder from npmignore

---

src/index.js

To mimic, go-ipfs, dir file size should not be defined.
If you're curious, this hasn't come up before because there was no data in dirs, but now there is in sharded dirs (the bucket bit field).

fix: dirs shouldn't have file size

---

src/unixfs.proto.js

The mimetype is [optional](https://github.com/ipfs/go-ipfs/blob/master/unixfs/pb/unixfs.proto#L23) in go-ipfs-unixfs so this PR makes it optional in js too.

chore: make mimetype optional as it is in go

---

package.json
src/index.js
test/unixfs-format.spec.js

Go:
```sh
$ touch emptyfile
$ ipfs add emptyfile 
added QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH emptyfile
$ ipfs object data QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH | xxd
00000000: 0802 1800 
```
Without this PR:
```sh
$ jsipfs add emptyfile 
added QmfJMCvenrj4SKKRc48DYPxwVdS44qCUCqqtbqhJuSTWXP emptyfile
$ jsipfs object data QmfJMCvenrj4SKKRc48DYPxwVdS44qCUCqqtbqhJuSTWXP | xxd
00000000: 0802 1200                                ....
```
With this PR:
```sh
$ jsipfs add emptyfile 
added QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH emptyfile
$ jsipfs object data QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH | xxd
00000000: 0802 1800   
```

Make consistent with go

---

.travis.yml
README.md
ci/Jenkinsfile
package.json
test/index.js

chore: switch to travis for ci

---

package.json
src/index.js
src/unixfs.proto.js
test/unixfs-format.spec.js

Adds two new fields `mtime` and `mode` in line with the unixfs spec.
One possible wart here is that `mtime` is implemented as a JavaScript number which means it can't hold the full value of `int64` so cannot represent dates in the far future.
This should be addressed by UnixFSv2 which should hopefully arrive before we top out `Number.MAX_SAFE_INTEGER` - e.g. early June 2255.

feat: adds metadata to unixfs

---

README.md
package.json
src/index.js
src/unixfs.proto.js
test/unixfs-format.spec.js

Upgrades `protons` to take advantage of new `hasFoo` type methods to detect if the user has set `mode` and `mtime` or not.
Also updates the constructor:
```javascript
// old
new UnixFS('file', buf)
// new
new UnixFS('file', buf) // still supported
new UnixFS() // defaults to 'file' without data
new UnixFS({ // all fields are optional, apart from `type`
type: 'file',
data: buf,
blockSizes: [],
mode: parseInt('0755', 8),
mtime: new Date()
})
```
This is to not have the [boolean-trap](https://ariya.io/2011/08/hall-of-api-shame-boolean-trap) style constructor of:
```javascript
new UnixFS(type, data, bufferSizes, mode, mtime)
```

fix: allow mtime and mode to be optional

---

src/index.js
test/unixfs-format.spec.js

Only expose documented bits to calling code but respect them when turning the entry into a protobuf.
Implements https://github.com/ipfs/specs/pull/231

fix: mask file mode

---

.gitignore
README.md
package.json
src/index.js
src/unixfs.proto.js
test/unixfs-format.spec.js

To allow high resolution `mtime`, store time as `TimeSpec` message which contains seconds and nanosecond fragments.
Also allows passing `mtime` and `mode`  in multiple formats, ~defaults `mtime` to the epoch~, fixes coverage npm script and increases module test coverage.
Depends on:
-  [x] https://github.com/ipfs/specs/pull/236

feat: store time as timespec

---

packages/ipfs-unixfs-importer/src/dag-builder/file/index.js
packages/ipfs-unixfs-importer/test/chunker-custom.spec.js
packages/ipfs-unixfs-importer/test/importer.spec.js

Following further conversation in https://github.com/ipfs/go-ipfs/issues/6940 it seems for small files it would be better to only ignore the `--raw-leaves` flag when metadata is actually present.
Partially reverts https://github.com/ipfs/js-ipfs-unixfs-importer/pull/49

fix: only ignore raw-leaves when file is small and metadata is present

---

packages/ipfs-unixfs-exporter/README.md
packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-exporter/src/index.js
packages/ipfs-unixfs-exporter/src/resolvers/dag-cbor.js
packages/ipfs-unixfs-exporter/src/resolvers/identity.js
packages/ipfs-unixfs-exporter/src/resolvers/index.js
packages/ipfs-unixfs-exporter/src/resolvers/raw.js
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/directory.js
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/file.js
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/index.js
packages/ipfs-unixfs-exporter/src/utils/find-cid-in-shard.js
packages/ipfs-unixfs-exporter/test/exporter.spec.js

Adds a `signal` option to the exporter that will be passed to `ipld.get`, allowing it to be notified that the user is no longer interested in exporting the file/directory/etc.
Current behaviour is that if the node is offline and a block is not in the repo is will throw, if it's online the CID will be added to the bitswap want list via the block service.
Follow up PRs to ipld, block service and bitswap will implement the removal logic.

feat: support aborting exports

---

packages/ipfs-unixfs-exporter/test/exporter-sharded.spec.js
packages/ipfs-unixfs-exporter/test/exporter-subtree.spec.js
packages/ipfs-unixfs-exporter/test/exporter.spec.js
packages/ipfs-unixfs-exporter/test/helpers/block.js
packages/ipfs-unixfs-importer/README.md
packages/ipfs-unixfs-importer/package.json
packages/ipfs-unixfs-importer/src/dag-builder/dir.js
packages/ipfs-unixfs-importer/src/dag-builder/file/buffer-importer.js
packages/ipfs-unixfs-importer/src/dag-builder/file/index.js
packages/ipfs-unixfs-importer/src/dag-builder/index.js
packages/ipfs-unixfs-importer/src/dir-flat.js
packages/ipfs-unixfs-importer/src/dir-sharded.js
packages/ipfs-unixfs-importer/src/index.js
packages/ipfs-unixfs-importer/src/tree-builder.js
packages/ipfs-unixfs-importer/src/utils/persist.js
packages/ipfs-unixfs-importer/test/builder-dir-sharding.spec.js
packages/ipfs-unixfs-importer/test/builder-only-hash.spec.js
packages/ipfs-unixfs-importer/test/builder.spec.js
packages/ipfs-unixfs-importer/test/chunker-custom.spec.js
packages/ipfs-unixfs-importer/test/hash-parity-with-go-ipfs.spec.js
packages/ipfs-unixfs-importer/test/helpers/block.js
packages/ipfs-unixfs-importer/test/import-export-nested-dir.spec.js
packages/ipfs-unixfs-importer/test/import-export.spec.js
packages/ipfs-unixfs-importer/test/importer.spec.js

This improves reusability of the module as it can be used by passing part of an `ipfs` or `ipfs-http-client` instance in.
It also means we no longer double serialize blocks before adding them which delivers a very small performance increase (1-2%).
Finally also documents the `pin` and `preload` arguments.
BREAKING CHANGE:
The importer takes a `pin` argument (previously undocumented) - it used to default to `true` but since this switches to use the block API the default has changed to `false`, as the typical usage pattern is to pin the root block of a DAG recursively instead of every block that makes up the DAG.

refactor: use the block API from ipfs instead of ipld internals

---

packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-importer/package.json
packages/ipfs-unixfs/package.json
packages/ipfs-unixfs/src/index.js
packages/ipfs-unixfs/test/unixfs-format.spec.js

The UnixFS Spec [says](https://github.com/ipfs/specs/blob/master/UNIXFS.md#metadata) high mode bits not defined in the version of the spec supported by a given implementation should be ignored but also persisted to ensure forwards compatibility.  The change here:
1. Ignores high bits passed to the constructor
1. Respects high bits read out of a protobuf though does not expose them
1. Writes high bits back to a protobuf but only if they were read from a protobuf to begin with

fix: ignore high mode bits passed to constructor

---

packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-importer/package.json

Updates to new dag-pb to incorporate changes that allows passing `Uint8Array`s in place of node `Buffer`s.
@achingbrain I'm not sure what's the deal with this file https://github.com/ipfs/js-ipfs-unixfs/blob/master/packages/ipfs-unixfs-exporter/package-lock.json but it doesn't seem to get updated when running `npm install` in the root & seems to break `npm istall` when run in the exporter dir.

chore: upgrade to dag-pb that supports Uint8Array

---

packages/ipfs-unixfs-importer/package.json

Downgrades merge-options because v3 removed node 12 support.
Refs: https://github.com/ipfs/js-ipfs/issues/3270
Refs: https://github.com/schnittstabil/merge-options/issues/23

chore: downgrade merge-options

---

packages/ipfs-unixfs-importer/test/importer.spec.js

test: adds a test for getting the same multihash from different CID versions

---

packages/ipfs-unixfs-importer/src/dag-builder/file/buffer-importer.js
packages/ipfs-unixfs-importer/test/importer.spec.js

When importing and reporting progress we pass the current filename as part of progress events in the [http server](https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-server/src/api/resources/files-regular.js#L254-L255)
To do the same thing with core we need access to the filename as part of the progress handler so here we add that.

feat: pass file name along with progress

---

packages/ipfs-unixfs-importer/src/index.js
packages/ipfs-unixfs-importer/test/hash-parity-with-go-ipfs.spec.js
packages/ipfs-unixfs-importer/test/importer.spec.js

We change some defaults based on the CID version passed, this seems
like the wrong approach and debugging problems turns into whack-a-mole.
Let the calling code decide the settings for the various knobs and levers
instead.
BREAKING CHANGES: We previously did things like set rawLeaves to true based
on the CID version, now we do not.

fix: just do what the user asked

---

packages/ipfs-unixfs-importer/src/tree-builder.js
packages/ipfs-unixfs-importer/test/importer.spec.js

It's never been clear why js-ipfs doesn't support multiple roots when
go-ipfs does.
This PR removes the check for multiple roots so if you import five
files without a leading directory in their paths or without the `wrapWithDirectory`
option, you'll get five CIDs back instead of an error.
BREAKING CHANGE: Importing files that would result in multiple roots no longer throws an error

feat: support multiple roots

---

.gitignore
lerna.json

Lerna doesn't work with npm automation tokens out of the box, need
to disable auth verification for the time being.
Refs: https://github.com/lerna/lerna/issues/2788

chore: fix rc publishing

---

.gitignore
.travis.yml
package.json
packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-importer/package.json
packages/ipfs-unixfs/package.json

It's faster - running `time npm i` shows a nice speed up:
lerna
```
npm timing command:install Completed in 183859ms
npm timing npm Completed in 184077ms
npm info ok
real	3m4.246s
user	2m48.066s
sys	0m58.948s
```
npm7 + workspaces
```
npm timing command:install Completed in 101724ms
npm timing npm Completed in 101914ms
npm info ok
real	1m42.075s
user	1m52.422s
sys	0m46.022s
```
The downside is it requires npm7 - it's bundled with node 15 but will
require users up upgrade if they are using node 14 or below.

chore: use npm 7 workspaces instead of lerna bootstrap

---

packages/ipfs-unixfs-exporter/README.md
packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-exporter/src/index.js
packages/ipfs-unixfs-exporter/src/resolvers/dag-cbor.js
packages/ipfs-unixfs-exporter/src/resolvers/index.js
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/file.js
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/hamt-sharded-directory.js
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/index.js
packages/ipfs-unixfs-exporter/src/utils/find-cid-in-shard.js
packages/ipfs-unixfs-exporter/test/exporter-sharded.spec.js
packages/ipfs-unixfs-exporter/test/exporter-subtree.spec.js
packages/ipfs-unixfs-exporter/test/exporter.spec.js
packages/ipfs-unixfs-exporter/test/helpers/block.js
packages/ipfs-unixfs-exporter/test/helpers/collect-leaf-cids.js
packages/ipfs-unixfs-exporter/test/import-export-dir-sharding.spec.js
packages/ipfs-unixfs-exporter/test/import-export-nested-dir.spec.js
packages/ipfs-unixfs-exporter/test/import-export.spec.js
packages/ipfs-unixfs-exporter/test/importer.spec.js
packages/ipfs-unixfs-exporter/tsconfig.json
packages/ipfs-unixfs-importer/test/benchmark.spec.js
packages/ipfs-unixfs-importer/test/builder-only-hash.spec.js
packages/ipfs-unixfs-importer/test/builder.spec.js
packages/ipfs-unixfs-importer/test/chunker-custom.spec.js
packages/ipfs-unixfs-importer/test/hash-parity-with-go-ipfs.spec.js
packages/ipfs-unixfs-importer/test/helpers/block.js

Adds timeout and signal options to exporter

fix: use ipfs-core-types instead of redefining ipld

---

packages/ipfs-unixfs-exporter/src/index.js
packages/ipfs-unixfs-exporter/src/resolvers/dag-cbor.js
packages/ipfs-unixfs-exporter/src/resolvers/identity.js
packages/ipfs-unixfs-exporter/src/resolvers/raw.js
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/index.js
packages/ipfs-unixfs-exporter/test/exporter-sharded.spec.js
packages/ipfs-unixfs-exporter/test/exporter-subtree.spec.js
packages/ipfs-unixfs-exporter/test/exporter.spec.js
packages/ipfs-unixfs-exporter/test/import-export-dir-sharding.spec.js
packages/ipfs-unixfs-exporter/test/import-export-nested-dir.spec.js
packages/ipfs-unixfs-exporter/test/importer.spec.js
packages/ipfs-unixfs-importer/test/hash-parity-with-go-ipfs.spec.js

On CIDs `toString()` does the same as `toBaseEncodedString()`. The new js-multiformats
based CID implementation only has `toString()`. This change should make future PRs
easier to review.
This was a simple search and replace.

chore: replace toBaseEncodedString() with toString()

---

packages/ipfs-unixfs/package.json
packages/ipfs-unixfs/src/unixfs.js

To prevent namespace conflicts with protobuf message names.
Refs https://github.com/ipfs/js-ipfs-bitswap/pull/323

fix: add pbjs namespace

---

packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-importer/package.json

Let's force update multiformats. Well, I know in theory this is not needed but skypack does not do a good job with getting latest releases sometimes: https://codepen.io/vascosantos/pen/abWWbJe?editors=0011
Currently this module does not work in skypack, but I would like to see if https://github.com/multiformats/js-multiformats/pull/105 also fixes it.

chore: update multiformats

---

packages/ipfs-unixfs-exporter/test/importer.spec.js
packages/ipfs-unixfs-importer/src/types.d.ts

This module supports more than just `AsyncIterable<Uint8Array>` so update the types to reflect that.
These sigs are used by the `interface-ipfs-core` test suite.

fix: update import types

---

package.json
packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-importer/package.json
packages/ipfs-unixfs/package.json

Currently, the published package.json has `"types": "dist/src/index.d.ts"` and should be `"types": "src/index.d.ts",` according to where the types really are.
The problem here is that we need to both:
- have type paths correct in the dist folder
- have type paths correct for local dev in src
Given the path will change, we need to guarantee this is updated in the build `package.json`. Using an approach like `multiformats` and `uint8arrays` having a `types` folder which is moved to `dist` is not possible because of the inline `d.ts` files in this repo, which will be inside `dist` folder as `dist/src/*.d.ts`, breaking the imports from the types around it.
With the above in mind, this PR adds a postbuild script where the package.json is changed in post build to have `dist` removed.

fix: types with ipjs build

---

.gitignore
.travis.yml
package.json
packages/ipfs-unixfs-exporter/.aegir.cjs
packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-exporter/src/utils/find-cid-in-shard.js
packages/ipfs-unixfs-exporter/test/importer.spec.js
packages/ipfs-unixfs-exporter/tsconfig.json
packages/ipfs-unixfs-importer/.aegir.cjs
packages/ipfs-unixfs-importer/package.json
packages/ipfs-unixfs-importer/src/options.js
packages/ipfs-unixfs-importer/tsconfig.json
packages/ipfs-unixfs/.aegir.cjs
packages/ipfs-unixfs/package.json
packages/ipfs-unixfs/tsconfig.json

Build types to the `types` folder, then copy it to the `dist` folder
during the `prepare` step.

fix: publish with types in package.json

---

packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-importer/package.json
packages/ipfs-unixfs/package.json

We have engines with npm7 because we use npm7 workspaces, but this should only be needed in the main package.json for development. Internal packages should be published as supporting npm6 given that there are linux environments that still do not support npm7. For more information see https://github.com/web3-storage/web3.storage/issues/387 where this issue was raised
Closes https://github.com/web3-storage/web3.storage/issues/387

fix: individual packages can use npm 6

---

packages/ipfs-unixfs-exporter/README.md
packages/ipfs-unixfs-importer/README.md
packages/ipfs-unixfs/README.md

Use ESM in docs and remove references to ipld and replace with blockstores.

docs: update readmes

---

packages/ipfs-unixfs-exporter/test/importer.spec.js
packages/ipfs-unixfs-importer/src/dag-builder/file/buffer-importer.js

When an imported file is big enough to need leaf nodes, and that
file is imported with metadata, we should only add that metadata
to the root of the file DAG and not to every leaf in the graph.

fix: do not add metadata to leaves

---

packages/ipfs-unixfs-importer/src/utils/to-path-components.js
packages/ipfs-unixfs-importer/test/utils.spec.js

This removes the extra `^` char from [this regex](https://github.com/ipfs/js-ipfs-unixfs/blob/master/packages/ipfs-unixfs-importer/src/utils/to-path-components.js#L5) that was causing us to treat the `^` as a path separator.
Closes #177, and will fix https://github.com/web3-storage/web3.storage/issues/375 when pulled into the web3.storage client.

fix: don't split paths on `^` characters

---

packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-importer/package.json
packages/ipfs-unixfs/package.json

Also removes coverage with nyc because we use `--cov` with aegir instead.

chore: update dep-check command

---

package.json
packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-importer/package.json
packages/ipfs-unixfs/package.json

We have `typesVersions` to allow deep requires from these modules, but
they cause incorrect paths to be detected by tsc (see #214).
Since #161 we control exports using the exports map, and we only export
the root from each module so deep requires are disallowed and consequently
`typesVersions` isn't necessary.
Since it's causing problems and we don't need it, remove it.  We can
revisit once we publish ESM-only but right now this fixes up the types
tsc generates.
Fixes #214

fix: remove typesVersions from package.json

---

.gitignore
packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/file.js
packages/ipfs-unixfs-exporter/src/utils/extract-data-from-block.js
packages/ipfs-unixfs-exporter/test/exporter.spec.js

A polishing of #237.  Uses `it-parallel` to load a whole list of children of a DAG node in parallel rather than one at a time.  Makes fetching large files much faster.
From the js-ipfs interop suite:
Before:
```console
exchange files
go -> js
cat file
✔ go -> js: 67.1 MB (25659ms)
go -> go2
cat file
✔ go -> go2: 67.1 MB (19835ms)
js -> go
cat file
✔ js -> go: 67.1 MB (17407ms)
js -> js2
cat file
✔ js -> js2: 67.1 MB (20237ms)
```
After:
```console
exchange files
go -> js
cat file
✔ go -> js: 67.1 MB (15328ms)
go -> go2
cat file
✔ go -> go2: 67.1 MB (18536ms)
js -> go
cat file
✔ js -> go: 67.1 MB (17211ms)
js -> js2
cat file
✔ js -> js2: 67.1 MB (12124ms)
```

fix: parallelise loading of dag-pb links when exporting

---

packages/ipfs-unixfs-exporter/src/types.ts
packages/ipfs-unixfs-exporter/src/utils/find-cid-in-shard.js
packages/ipfs-unixfs-importer/src/index.js

If we don't to this, we end up importing deep paths from `unixfs` in the generated types which aren't in the exports map so fail when people are compiling their dependencies.
Fixes #214

fix: specify return type of the importer to generate correct types

---

packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/file.js

Refactor exporting files to use a queue instead of recursion to walk the DAG.  The queue exectutes on a new stack so we won't run out of memory when traversing very deep DAGs.

fix: prevent OOM on very deep DAGs

---

README.md
lerna.json
package.json
packages/ipfs-unixfs-exporter/README.md
packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-importer/README.md
packages/ipfs-unixfs-importer/package.json
packages/ipfs-unixfs-importer/src/chunker/fixed-size.js
packages/ipfs-unixfs-importer/src/chunker/rabin.js
packages/ipfs-unixfs-importer/src/types.ts
packages/ipfs-unixfs/README.md
packages/ipfs-unixfs/package.json

Also updates uint8arrays and all the it-* deps.
BREAKING CHANGE: CIDs returned are instances from `multiformats@10.x.x` and not `multiformats@9.x.x`

deps!: update multiformats to 10.x.x and all @ipld/* modules

---

packages/ipfs-unixfs-importer/README.md
packages/ipfs-unixfs-importer/src/dag-builder/index.ts
packages/ipfs-unixfs-importer/src/index.ts

These have slightly more obvious names.

fix: export importFile and importDirectory function

---

packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/directory.ts
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/hamt-sharded-directory.ts

This PR extends the work done in https://github.com/ipfs/js-ipfs-unixfs/pull/249 to also include directories and sharded directories.

fix: parallelise loading of dag-pb links in directories when exporting

---

packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-exporter/src/index.ts
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/file.ts
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/hamt-sharded-directory.ts
packages/ipfs-unixfs-exporter/src/utils/find-cid-in-shard.ts
packages/ipfs-unixfs-importer/package.json
packages/ipfs-unixfs-importer/src/dag-builder/dir.ts
packages/ipfs-unixfs-importer/src/dag-builder/file.ts
packages/ipfs-unixfs-importer/src/dag-builder/index.ts
packages/ipfs-unixfs-importer/src/dir.ts
packages/ipfs-unixfs-importer/src/index.ts
packages/ipfs-unixfs-importer/src/tree-builder.ts
packages/ipfs-unixfs-importer/src/utils/persist.ts

Instead of expecting a full `interface-blockstore` implementation, only require the subset of the methods that are actually used.

fix: use simpler blockstore interface

---

packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-importer/package.json
packages/ipfs-unixfs-importer/src/index.ts

This is a breaking change because the return type of `interface-blockstore` methods can now be promises or simple values which can affects the type of blockstore object that is accepted by the importer/exporter - internally the results are `await`ed on but the difference in types can upset typescript in some cases so it's safer to release it as a major.
BREAKING CHANGE: please use the latest `interface-blockstore` versions of everything, aside from this impact should be minimal

deps!: update blockstore

---

packages/ipfs-unixfs-exporter/src/index.ts

This option is not used, pass an AbortSignal instead

fix: remove unused timeout option from exporter

---

packages/ipfs-unixfs-exporter/src/index.ts
packages/ipfs-unixfs-importer/src/dag-builder/buffer-importer.ts
packages/ipfs-unixfs-importer/src/dag-builder/dir.ts
packages/ipfs-unixfs-importer/src/dag-builder/file.ts
packages/ipfs-unixfs-importer/src/dir-flat.ts
packages/ipfs-unixfs-importer/src/index.ts
packages/ipfs-unixfs-importer/test/builder-balanced.spec.ts
packages/ipfs-unixfs-importer/test/chunker-custom.spec.ts

The importer only needs `.put`, the exporter only needs `.get`

fix: reduce required number of blockstore methods

---

packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/file.ts
packages/ipfs-unixfs-exporter/test/exporter-esoteric.spec.ts

To ensure that blocks are emitted in the correct order while also not overflowing the stack, when we loop over the children of a node, use a separate queue for each child and wait for the queue to be idle before moving on to the next child.

fix: add tests for unbalanced dags and very deep dags

---

packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/file.ts
packages/ipfs-unixfs-exporter/test/exporter-esoteric.spec.ts

When we read too much or too little data, it normally means that the UnixFS metadata in the root node is incorrect, so throw an error.

fix: test for file under/over reads

---

packages/ipfs-unixfs-importer/README.md

* import `fs`
* remove undefined variables: `file`, `file2`, and `options`
* fix typo causing error "no such file or directory, open './foo/quxx'"

docs: example in README of ipfs-unixfs-importer

---

packages/ipfs-unixfs-importer/src/index.ts

Where we know the type of content to be imported ahead of time (e.g. a Uint8Array or a stream, not both), it can be helpful to specify that type, so make `FileCandidate` generic to allow this.
Defaults it to the previous `ImportContent` value so this is non-breaking.

fix: add optional type for file candidate data

---

packages/ipfs-unixfs-importer/src/chunker/rabin.ts
packages/ipfs-unixfs-importer/test/chunker-rabin.spec.ts

- test(ipfs-unixfs-importer): chunker-rabin constructor empty args
- fix(chunker-rabin): types and errors are aligned
fixes #339

fix(chunker-rabin): types and errors are aligned

---

packages/ipfs-unixfs-exporter/test/exporter-sharded.spec.ts
packages/ipfs-unixfs-importer/src/dir-sharded.ts
packages/ipfs-unixfs-importer/src/index.ts
packages/ipfs-unixfs-importer/src/tree-builder.ts

Adjusts the terminology in #356 to go with "bits".
Sorry for the stacked PRs, wanted to get this up here while I move on to working on some fixturing that is attempting to do a smaller fanout yielding the same root CID across JS & Go implementations .. struggling a bit to figure out where it's diverging.

fix: use fanout "bits"

---

packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/hamt-sharded-directory.ts
packages/ipfs-unixfs-exporter/test/exporter-sharded.spec.ts
packages/ipfs-unixfs-importer/src/dir-sharded.ts
packages/ipfs-unixfs-importer/src/flat-to-shard.ts
packages/ipfs-unixfs-importer/src/index.ts
packages/ipfs-unixfs-importer/src/tree-builder.ts

Adds a `shardFanoutBytes` option to the importer to allow configuring the number of bytes used for the HAMT prefix, also a test.

feat: add config option to control fanout size

---

packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/hamt-sharded-directory.ts
packages/ipfs-unixfs-exporter/src/utils/find-cid-in-shard.ts
packages/ipfs-unixfs-exporter/test/exporter-sharded.spec.ts
packages/ipfs-unixfs-importer/src/dir-sharded.ts
packages/ipfs-unixfs-importer/src/flat-to-shard.ts
packages/ipfs-unixfs-importer/src/index.ts
packages/ipfs-unixfs-importer/src/tree-builder.ts
packages/ipfs-unixfs/src/index.ts

Use the `fanout` value to slice off the correct number of characters from `Name` in HAMTs.
Fixes exporting the HAMT from https://github.com/ipld/ipld/blob/master/specs/transport/trustless-pathing/fixtures/unixfs_20m_variety.car (which has a small fanout to force collisions).
```console
$ ipfs-car ls unixfs_20m_variety.car 
.
./3l3ph4nt.txt
./5.docx
./Brabantio.docx
./Flibbertigibbet5
./Flibbertigibbet5/4.csv
./Flibbertigibbet5/5t4ck.pdf
./Flibbertigibbet5/Balderdash.json
./Flibbertigibbet5/Ballyhoo
./Flibbertigibbet5/Falstaff.pdf
./Flibbertigibbet5/Glimperwick.xml
./Flibbertigibbet5/Higgledy7.json
./Flibbertigibbet5/J.json
./Flibbertigibbet5/Lilliputian.xml
./Flibbertigibbet5/Splendiferous.png
./Flibbertigibbet5/W.png
./Flibbertigibbet5/aa.pdf
./Flibbertigibbet5/astronomicalunit.xml …
```

feat: add a shardFanoutBits option to the importer

---

packages/ipfs-unixfs-exporter/test/exporter-sharded.spec.ts
packages/ipfs-unixfs-importer/src/utils/to-path-components.ts

Ref: https://github.com/ipfs/go-unixfsnode/pull/66
The material change in here is the path cleaner/splitter; it's a bit too aggressive. It doesn't allow `\` as a file name and the `.trim()` discounts valid file names. Otherwise this is a match for https://github.com/ipfs/go-unixfsnode/pull/66 and gets the same CID on importer, and tests the exporter can read the same data.

fix: add cross-impl shard test, fix path cleaner

---

packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-exporter/src/resolvers/dag-json.ts
packages/ipfs-unixfs-exporter/src/resolvers/index.ts
packages/ipfs-unixfs-exporter/test/exporter.spec.ts

Basically the same as `dag-cbor`...allows the exporter to `walkPath` and export `dag-json` encoded data.

feat: add dag-json resolver

---

packages/ipfs-unixfs-exporter/README.md
packages/ipfs-unixfs-exporter/package.json
packages/ipfs-unixfs-exporter/src/index.ts
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/directory.ts
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/file.ts
packages/ipfs-unixfs-exporter/src/resolvers/unixfs-v1/content/hamt-sharded-directory.ts
packages/ipfs-unixfs-exporter/test/exporter.spec.ts

By default we attempt to load all sibilings in a given layer of a DAG at once to allow slow/async loading routines extra time to fetch data before it is needed.
Some blockstores (e.g. CAR files) require the exporter to only request the next sequential CID in a DAG.
Add a `blockReadConcurrency` option (named similarly to the importer's `blockWriteConcurrency` option) to control this behaviour.
Fixes #359

feat: add blockReadConcurrency option to exporter

---

packages/ipfs-unixfs/src/errors.ts
packages/ipfs-unixfs/src/index.ts
packages/ipfs-unixfs/test/unixfs-format.spec.ts

Matches the undocumented limit in boxo.
Fixes #421

fix: limit incoming hamt width
